
// Generate code by cmake, don't modify
#ifndef BASE_VERSION_H
#define BASE_VERSION_H


#define PLANCK_VERSION_MAJOR_RC  ${PLANCK_VERSION_MAJOR}
#define PLANCK_VERSION_MINOR_RC ${PLANCK_VERSION_MINOR}
#define PLANCK_VERSION_PATCH_RC ${PLANCK_VERSION_PATCH}


#define PLANCK_VERSION L"${PLANCK_VERSION_MAJOR}.${PLANCK_VERSION_MINOR}.${PLANCK_VERSION_PATCH}"
#define PLANCK_HASH L"${GIT_SHA1}"
#define PLANCK_REFS L"${GIT_REFSPEC}"

#define PLANCK_APPNAME L"Planck-${PLANCK_VERSION_MAJOR}.${PLANCK_VERSION_MINOR}"

#endif
